In [1]:
import tensorflow as tf

C:\Users\StrikeWade\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [3]:
const = tf.constant(value=10)
fill_mat = tf.fill(dims=[4,4], value=10)
myzeros = tf.zeros(shape=[4,4])
myones = tf.ones(shape=[4,4])
myrandn = tf.random_normal(shape=[4,4], mean=0, stddev=1.0)
myrandu = tf.random_uniform(shape=[4,4], minval=0, maxval=1)

In [5]:
my_ops = [const, fill_mat, myzeros, myones, myrandn, myrandu]

In [6]:
my_ops

[<tf.Tensor 'Const:0' shape=() dtype=int32>,
 <tf.Tensor 'Fill:0' shape=(4, 4) dtype=int32>,
 <tf.Tensor 'zeros:0' shape=(4, 4) dtype=float32>,
 <tf.Tensor 'ones:0' shape=(4, 4) dtype=float32>,
 <tf.Tensor 'random_normal:0' shape=(4, 4) dtype=float32>,
 <tf.Tensor 'random_uniform:0' shape=(4, 4) dtype=float32>]

In [11]:
# Not need to call Session() all the time
sess = tf.InteractiveSession()

In [14]:
for op in my_ops:
#     print(op.eval())
    print(sess.run(op))
    print('')

10

[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

[[ 0.08525268  0.26073474  0.7314731   1.4803791 ]
 [-1.8259399   0.1962847   0.8998909   0.44494474]
 [-0.95551974 -0.20673999 -1.1848744   0.44290125]
 [-0.24958736 -0.4646222   1.9773011   1.5132205 ]]

[[0.8618418  0.4588164  0.74214745 0.8427763 ]
 [0.5856292  0.82293296 0.21870697 0.6478083 ]
 [0.65089285 0.26097846 0.07757723 0.67623746]
 [0.04927576 0.82187533 0.8114656  0.6763084 ]]



# TF Graphs

In [15]:
#used graph
tf.get_default_graph()

In [17]:
#Create a new graph
g = tf.Graph()
g

In [22]:
graph_one = tf.get_default_graph()
graph_one

In [23]:
graph_two = g
graph_two

In [30]:
#Set graph_two as default
with graph_one.as_default():
    print(graph_one is tf.get_default_graph())

True


In [32]:
#Which graph are we on ?
print(graph_two is tf.get_default_graph())

False


# TF placeholder, variable, initialize variables

In [33]:
mytensor = tf.random_uniform(shape=[4,4], minval=0, maxval=1)

In [38]:
my_var = tf.Variable(initial_value=mytensor)
sess.run(my_var)
#Error occurs because the variable is not initialized

FailedPreconditionError: Attempting to use uninitialized value Variable_2
	 [[Node: Variable_2/_14 = _Send[T=DT_FLOAT, client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_4_Variable_2", _device="/job:localhost/replica:0/task:0/device:GPU:0"](Variable_2)]]
	 [[Node: Variable_2/_15 = _Recv[_start_time=0, client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_4_Variable_2", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

In [39]:
#Initialize
init = tf.global_variables_initializer()
sess.run(init)

In [40]:
sess.run(my_var)

array([[0.88330317, 0.74090266, 0.53933   , 0.5410881 ],
       [0.21382034, 0.85739124, 0.36627638, 0.54791784],
       [0.01128173, 0.05588388, 0.12598348, 0.03666902],
       [0.8134575 , 0.05583119, 0.8101933 , 0.9225671 ]], dtype=float32)

In [41]:
placeholder = tf.placeholder(dtype=tf.float32, shape=[None, 5]) # None because this first one can be filled with the actual number samples in the data 